### ISSUE TITLE
unable to do the extract file and Install

### ISSUE THREAD

**Issue by Mehdi-Ghazlavi** [stalker780/opencart-vqmod-manager#2]
Hello Im i installed the extension on my site but every time i click on extract file it show me "permission denied". i did some search and change the permission of mysite.com/index.php and mysite.com/dashboerd/index.php to 777 but still not working

**Comment by Khnaz35** [comment]
How did you install this extension ? You need to provide more information/details steps taken.

**Comment by Mehdi-Ghazlavi** [comment]
Rename downloaded file to clicker_vqmod_manager.ocmod.zip
Open Extensions->Installer
Upload clicker_vqmod_manager.ocmod.zip
Find uploaded extension in a list and click Install
Open Extensions->Extensions->Modules
Find VQModManager module and click install
Now open module and follow VQMod installation steps 
From Here on I get permission denied

**Comment by stalker780** [comment]
Is this a full error message "Permission denied"?
Or there is more description including line of code where this error happens?

Your folders should have 755 permission including OC root folder. Files 644.

**Comment by Khnaz35** [comment]
If you are facing permission issue you can do one thing. Modify the permissions by going to **System/user group** and try again

**Comment by Mehdi-Ghazlavi** [comment]
Yes The full message is "Permission denied" And I change The root file permission to 755, and the mysite.com/index.php and mysite.com/dashboerd/index.php  to 755, and Modified the permission of user group still having same error

**Comment by stalker780** [comment]
If your root folder does not have write permission 755 PHP cannot create root/vqmod folder during installation. 
This could cause an error.
