### ISSUE TITLE
vqmod for extension folder

### ISSUE THREAD

**Issue by aitspk** [stalker780/opencart-vqmod-manager#3]
the vqmod xml have no effect on extension folder so is there a way to write vqmod for files in extension folder

**Comment by stalker780** [comment]
You are doing something wrong. 
Works fine for me. 
Check your XML or VQMod installation.

```
	<file name="extension/opencart/admin/view/template/dashboard/map_info.twig" error="log">
		<operation error="log">
			<search position="before" trim="true"><![CDATA[
				<div class="card-header"><i class="fa-solid fa-globe"></i> {{ heading_title }}</div>
			]]></search>
			<add trim="true"><![CDATA[
				<div class="card-header">MY TEST EXTENSION HEADER</div>
			]]></add>
		</operation>
	</file>
```

![image](https://user-images.githubusercontent.com/6297070/236687407-22b2bd35-f0ae-4e03-bd07-7976bb9af504.png)

**Comment by aitspk** [comment]
Thank just was an issue with location yes it is working
