### ISSUE TITLE
error 449 after install

### ISSUE THREAD

**Issue by shinobi31337** [stalker780/opencart-vqmod-manager#4]
Hi, 
succesfully installed the latest opencart and uploaded vqmod4 with installer, but cannot enable it. Iin the Maintenance tab when click to 1. Extract VQMod (vqmod-2.6.8-opencart.zip) or 2.Run installer - it is showing the window with error message:

HTTP code: 449 Response text:

**Comment by stalker780** [comment]
I suppose it is related to your hosting/webserver setup and permissions, not vqmod manager.

HTTP Code 449 is absolutely not typical for usual Apache/Nginx/PHP setup.

Without any information about your server software it is just a guessing game.
